### ISSUE TITLE
Could not working in past 3 days for all wordpress site 

### ISSUE THREAD

**Issue by sathishmass** [isaumya/adsense-invalid-click-protector#3]
I think it has an issue with the newest Wordpress version or anything else. In the recent 3 days, the plugin doesn't work properly. Please fix the issue as soon a possible. we will contribute money to that. 

This plugin is working perfectly, so please refer to this plugin and fix the bug in your plugin sir. because we love aicp Indian products so much. 

Thank you

**Comment by isaumya** [comment]
Hi,
Do you see any error in the chrome developer console or something like that? Just saying it's not working doesn't help. Please also share how to reproduce the issue.

**Comment by sathishmass** [comment]
![image](https://user-images.githubusercontent.com/63893887/79629064-f297c700-8163-11ea-89de-02b1d063e5db.png)
 Yesterday I have 70k page views, instead of 70,000 page views my blocked IP is the only 10ip. I have dual checked my ad placement and disabled cache plugin. in my all 6 site sites also facing this issue and my friend website also facing this same issue. 

I have noticed since last weekday by day the blocked IPs are reducing lower than usual days. Last week I have more than 80ips and 2nd day it has gone to 50 and  30. now my number of blocked IP is only 4 in a day. most of the app-enabled sites also facing this issue only in recent days. 

sir, please check the issue, when the aicp working fine and my car is below 5%. now the aicp isn't working now my AdSense ctr is above 10%. 

please check my issue 
j[obs.recipescorner.in](url) and [jobzseeking.com](url)

**Comment by sathishmass** [comment]
it has been getting this error in developer console ??
![image](https://user-images.githubusercontent.com/63893887/79629413-2b856b00-8167-11ea-81e6-b530ef92879d.png)

**Comment by isaumya** [comment]
> ![image](https://user-images.githubusercontent.com/63893887/79629064-f297c700-8163-11ea-89de-02b1d063e5db.png)
> Yesterday I have 70k page views, instead of 70,000 page views my blocked IP is the only 10ip. I have dual checked my ad placement and disabled cache plugin. in my all 6 site sites also facing this issue and my friend website also facing this same issue.
> 
> I have noticed since last weekday by day the blocked IPs are reducing lower than usual days. Last week I have more than 80ips and 2nd day it has gone to 50 and 30. now my number of blocked IP is only 4 in a day. most of the aicp-enabled sites also facing this issue only in recent days.
> 
> sir, please check the issue, when the aicp working fine and my car is below 5%. now the aicp isn't working now my AdSense ctr is above 10%.
> 
> please check my issue
> j[obs.recipescorner.in](url) and [jobzseeking.com](url)

Your fiend's website also use AICP? If you take out AICP from the equation does your other IP related problem gets solved?

**Comment by isaumya** [comment]
> it has been getting this error in developer console ??
> ![image](https://user-images.githubusercontent.com/63893887/79629413-2b856b00-8167-11ea-81e6-b530ef92879d.png)

It is saying your server has some bad gateway issues for that page.

**Comment by sathishmass** [comment]
> > ![image](https://user-images.githubusercontent.com/63893887/79629064-f297c700-8163-11ea-89de-02b1d063e5db.png)
> > Yesterday I have 70k page views, instead of 70,000 page views my blocked IP is the only 10ip. I have dual checked my ad placement and disabled cache plugin. in my all 6 site sites also facing this issue and my friend website also facing this same issue.
> > I have noticed since last weekday by day the blocked IPs are reducing lower than usual days. Last week I have more than 80ips and 2nd day it has gone to 50 and 30. now my number of blocked IP is only 4 in a day. most of the aicp-enabled sites also facing this issue only in recent days.
> > sir, please check the issue, when the aicp working fine and my car is below 5%. now the aicp isn't working now my AdSense ctr is above 10%.
> > please check my issue
> > j[obs.recipescorner.in](url) and [jobzseeking.com](url)
> 
> Your fiend's website also use AICP? If you take out AICP from the equation does your other IP related problem gets solved?

Yes my friend also using aicp and most of the aicp using tube friends site also not working with aicp. 
i used ad inseter and many ad plugin. Only 2 or 4 IP are blocking.

please suggest any solution for what now i should do with my site?
or can u tell me any steps to fix the issue or to make a changes in my site?

**Comment by sathishmass** [comment]
> > it has been getting this error in developer console ??
> > ![image](https://user-images.githubusercontent.com/63893887/79629413-2b856b00-8167-11ea-81e6-b530ef92879d.png)
> 
> It is saying your server has some bad gateway issues for that page.

**Comment by sathishmass** [comment]
Bro mark my words I'm not joking. I have using the aicp plugin for 2 years and I well knew to configure the plugin. This week at the same time all of my websites the aicp plugin isn't working not blocking the ads too and i  checked some nulled paid plugin that works fine. Only in ur plugin, there is a bug.

SIR it's MY REQUEST PLEASE LOOK AT UR CODE AND ALSO PLEASE TEST THE PUGIN SIR. This problem occurs most of the Wordpress users. 

please sir....

**Comment by isaumya** [comment]
@sathishmass I've released v1.2.4 of the plugin. Please download the update and use it. I hope it will resolve your problem.
