### ISSUE TITLE
Support for Classicpress

### ISSUE THREAD

**Issue by cwebdesign** [isaumya/adsense-invalid-click-protector#7]
Can you please add support for Classicpress? The latest version does not work with Classicpress. Older versions cannot be used due to the vulnerabilities they include.

**Comment by isaumya** [comment]
The new security patch of the plugin does not include anything that will make it stop working with Classicpress. What makes you think that it is a plugin issue?

**Comment by cwebdesign** [comment]
The version which is available is 1.2.3. No more recent versions are available.
There is also a warning which says:
Error: This plugin requires a newer version of WordPress and may not be compatible with ClassicPress.

**Comment by isaumya** [comment]
Hi, the current version of [AICP plugin](https://wordpress.org/plugins/ad-invalid-click-protector/) is 1.2.7.
If you are seeing such an error message you need to ask the ClassicPress team about what is exactly causing the issue. As there were no major changes being made in the plugin besides security strengthening.

**Comment by cwebdesign** [comment]
On wordpress your plugin indicates 5.0 wordpress minimum. That's why it can't be used, I presume. I have posted in the ClassicPress forums so perhaps this can be resolved. Thank you.

**Comment by isaumya** [comment]
@cwebdesign just released v1.2.8 of the plugin with a minimum WP requirement of v4.9. So, now you can use it on Classicpress.
